[licenses]
allow = [
  "Apache-2.0",
  "MIT",
  "BSD-3-Clause",
  "BSD-2-Clause",
  "ISC",
  "Zlib",
  "0BSD",
  "Unlicense",
  "Apache-2.0 WITH LLVM-exception",
]
confidence-threshold = 0.8

[sources]
unknown-registry = "deny"
unknown-git = "deny"

[bans]
multiple-versions = "warn"
